
name: Send News Mail

on:
  schedule:
    # 한국 시간(KST) 매일 오전 8시에 실행 (UTC 기준 23:00)
    - cron: '0 23 * * *'
  workflow_dispatch: # 수동 실행을 위한 옵션

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create credentials.json
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > src/credentials.json

      - name: Create token.json
        run: echo '${{ secrets.TOKEN_JSON }}' > src/token.json

      - name: Run main script
        run: python src/main.py
